### ISSUE TITLE
Use more natural triggers

### ISSUE THREAD

**Issue by idleberg** [ahmadawais/Sublime-WP-Customizer#1]
_This is not exactly an issue, but rather a suggestion to make these snippets more accessible to anyone already familiar with WordPress Customizer function syntax_

Why do you force potential users to learn cryptic triggers to fire these snippets? Abbreviations are fine, everybody wants to type as little as possible. However, leave the work to Sublime Text's fuzzy logic and let everybody use their preferred way to abbreviate, rather than making them learn an _additional_ naming system on top of Customizer function syntax.

**Example**:
- `npwpcasection` completes to a `$wp_customize->add_control` block for a customizer section
- If the trigger for this snippet was loosely based on the function syntax (e.g. `wp-customize-add-control-section`), you could fire the snippet using almost the same cryptic abbreviation (**wp**-**c**ustomize-**a**dd-**c**ontrol-**section** = **wpcasection**)
- Personally, I'd probably want use `wpaddsection` instead, a third person might have a different preference

Snippets, opposed to completions, require a meaningful prefix to limit the choices in the completion pop-up and to avoid accidentally firing a snippet. I'm not sure about your motivation to use the `npwp` prefix, which is why I omitted the `np`-part in the example above – apart from feeling more WordPress-y.

I hope this does make sense to you. WordPress Customizer functions can be frustrating to write, so I welcome this package. However, I think it could be done better. Would love to hear your thoughts.

**Comment by ahmadawais** [comment]
@idleberg I appreciate your concerns. I thought long and hard before going along with `npwp` style snippets. Actually, it is based on the fuzzy search of Sublime Text. `np` is the fuzzy search acronym for `snippet`. I added that to make the fuzzy search more reliable. Otherwise it was getting mixed with other WP packages. 

So, read it like this. Snippet `np` WordPress `wp` Customizer `c` and then what you want to add. 

I tried adding trigger on `$wp_customize->add_control` but it doesn't work in Sublime. Since these snippets are much more than just one single line function, that is why I decided to go more semantic instead of syntax specific. 

Now, since you know that. What do you think about it?

**Comment by ahmadawais** [comment]
BTW you can do an initials based search.E.g. 

![](http://recordit.co/cFf2hXQ9QA.gif)

**Comment by ahmadawais** [comment]
@idleberg BTW let me know if you have more suggestions on how to do it? Maybe, I can duplicate the snippets so that one could have both `np` and `wp` versions. On my end though, `wp` versions got mixed with other pacakges.

**Comment by idleberg** [comment]
> Otherwise it was getting mixed with other WP packages.

I see, that makes perfect sense then

> I tried adding trigger on $wp_customize->add_control but it doesn't work in Sublime

Yes, by default snippets aren't triggered by `word_separators`, though this could be overridden by the the package settings. So you could actually use `$wp` as prefix if you wanted to.

Thanks for giving some insight in your decision making, sounds like you put some thought into it. I'll see if I get used to the triggers, otherwise I could still create my own private fork.

Anyway, thanks for the package, it already made my life much easier!

**Comment by ahmadawais** [comment]
@idleberg I will look into having two snippets one with `np` and other without `np`. 
I have a few more packages planned, lots of local workflows that I want to share. 

Glad it made sense to you after I explained. Actually, I am still writing the article about it. There is also a [WPCustomize Library or Boilerplate](https://github.com/ahmadawais/WPCustomize) for those who are interested in Customizer. I will be growing my components library in that repo, along with more snippets to the sublime package.

I see you have quite a few Sublime packages under your belt as well. This one was my first, so I am getting into Sublime packages slowly. Saw in one of your packages that `messages.json` file can be used to display a success message. Was searching for that.

**Comment by ahmadawais** [comment]
Also, can you elaborate on this one

> Yes, by default snippets aren't triggered by word_separators, though this could be overridden by the the package settings. So you could actually use $wp as prefix if you wanted to.

**Comment by ahmadawais** [comment]
@idleberg I tried removing `np` and it worked pretty good. So, in version `1.0.2` I have removed `np` prefix and added a new snippet.
